import { defineConfig } from 'vitest/config';
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig({
  plugins: [tsconfigPaths()],
  resolve: {
    alias: {
      '@nestjs/event-emitter': '/Users/tanim/WorkSpace/Personal/VibeCoding/Claude Code/hr-backend/apps/api/src/__mocks__/event-emitter.mock.ts',
    },
  },
  test: {
    globals: true,
    environment: 'node',
    include: ['apps/**/src/**/*.spec.ts', 'libs/**/src/**/*.spec.ts'],
    exclude: ['**/node_modules/**', '**/dist/**', 'apps/api/src/__tests__/regression/**'],
    setupFiles: ['./test/vitest-setup.ts'],
    env: {
      NODE_ENV: 'test',
      DATABASE_URL: 'postgresql://user:pass@localhost:5432/db',
      REDIS_URL: 'redis://localhost:6379',
      MINIO_ENDPOINT: 'localhost',
      MINIO_ACCESS_KEY: 'access',
      MINIO_SECRET_KEY: 'secret',
      JWT_PRIVATE_KEY_PATH: 'keys/private.pem',
      JWT_PUBLIC_KEY_PATH: 'keys/public.pem',
      COOKIE_SECRET: '12345678901234567890123456789012',
      ENCRYPTION_KEY: '01234567890123456789012345678901',
      MAIL_HOST: 'localhost',
      MAIL_FROM: 'test@example.com',
      LOG_LEVEL: 'info',
    },
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov', 'html'],
      reportsDirectory: './coverage',
      thresholds: {
        lines: 90,
        functions: 90,
        branches: 90,
        statements: 90,
      },
      include: [
        'apps/api/src/modules/auth/auth.service.ts',
        'apps/api/src/modules/auth/token.service.ts',
        'apps/api/src/modules/auth/password.service.ts',
        'apps/api/src/modules/auth/guards/jwt-auth.guard.ts',
        'apps/api/src/modules/auth/guards/permissions.guard.ts',
        'apps/api/src/modules/auth/interceptors/audit.interceptor.ts',
        'apps/api/src/modules/leave/services/leave-accrual.engine.ts',
        'apps/api/src/modules/leave/services/leave-request.service.ts',
        'apps/api/src/modules/attendance/services/attendance.service.ts',
        'libs/prisma/src/extensions/tenant-scope.extension.ts',
        // Sprint 5 modules
        'apps/api/src/modules/esign/esign.service.ts',
        'apps/api/src/modules/policy/policy.service.ts',
        'apps/api/src/modules/notifications/notifications.service.ts',
        'apps/api/src/modules/notifications/processors/email-dispatch.processor.ts',
        'apps/api/src/modules/audit/audit.service.ts',
        'apps/api/src/modules/documents/documents.service.ts',
        // Sprint 6 modules
        'apps/api/src/modules/reports/services/report-query.service.ts',
        'apps/api/src/modules/reports/services/saved-report.service.ts',
        'apps/api/src/modules/reports/services/report-schedule.service.ts',
        'apps/api/src/modules/reports/workers/report-export.processor.ts',
        'apps/api/src/modules/reports/workers/schedule-dispatcher.processor.ts',
        'apps/api/src/modules/mss/mss.service.ts',
      ],
      exclude: [
        '**/*.spec.ts',
        '**/*.module.ts',
        '**/main.ts',
        '**/index.ts',
        '**/*.dto.ts',
        '**/*.entity.ts',
        '**/*.interface.ts',
        '**/*bootstrap.ts',
        '**/response.types.ts',
        '**/api-error-responses.decorator.ts',
        '**/all-exceptions.filter.ts',
        '**/otel.ts',
        '**/span.decorator.ts',
      ],
    },
  },
});
