import Joi from 'joi';

export const envSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').required(),
  PORT: Joi.number().port().default(3000),
  HOST: Joi.string().hostname().default('0.0.0.0'),
  API_BASE_URL: Joi.string().uri().optional(),
  WEB_BASE_URL: Joi.string().uri().optional(),
  CORS_ORIGIN: Joi.string().optional(),
  SWAGGER_ENABLED: Joi.boolean().truthy('true').falsy('false').default(false),
  DATABASE_URL: Joi.string().uri({ scheme: ['postgresql', 'postgres'] }).required(),
  DATABASE_POOL_MIN: Joi.number().integer().min(1).default(2),
  DATABASE_POOL_MAX: Joi.number().integer().min(1).default(10),
  REDIS_URL: Joi.string().uri({ scheme: ['redis', 'rediss'] }).required(),
  MINIO_ENDPOINT: Joi.string().required(),
  MINIO_PORT: Joi.number().port().default(9000),
  MINIO_ACCESS_KEY: Joi.string().required(),
  MINIO_SECRET_KEY: Joi.string().required(),
  MINIO_USE_SSL: Joi.boolean().truthy('true').falsy('false').default(false),
  MINIO_BUCKET_NAME: Joi.string().default('hr-uploads'),
  JWT_PRIVATE_KEY_PATH: Joi.string().required(),
  JWT_PUBLIC_KEY_PATH: Joi.string().required(),
  COOKIE_SECRET: Joi.string().min(32).required(),
  MAIL_HOST: Joi.string().required(),
  MAIL_PORT: Joi.number().port().default(587),
  MAIL_FROM: Joi.string().required(),
  MAIL_USER: Joi.string().optional(),
  MAIL_PASS: Joi.string().optional(),
  SSO_ENABLED: Joi.boolean().truthy('true').falsy('false').default(false),
  GOOGLE_CLIENT_ID: Joi.when('SSO_ENABLED', {
    is: true,
    then: Joi.string().required(),
    otherwise: Joi.string().optional(),
  }),
  GOOGLE_CLIENT_SECRET: Joi.when('SSO_ENABLED', {
    is: true,
    then: Joi.string().required(),
    otherwise: Joi.string().optional(),
  }),
  LOG_LEVEL: Joi.string()
    .valid('fatal', 'error', 'warn', 'info', 'debug', 'trace')
    .default('info'),
  OTEL_SERVICE_NAME: Joi.string().default('hr-api'),
  OTEL_EXPORTER_OTLP_ENDPOINT: Joi.string().uri().optional(),
  OTEL_TRACES_SAMPLER_ARG: Joi.number().min(0).max(1).default(1.0),
}).options({ allowUnknown: false });
